# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20151203_0623'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenume', models.TextField(max_length=100)),
                ('nume', models.TextField(max_length=100)),
                ('data_nasterii', models.DateField()),
                ('sex', models.CharField(choices=[(b'M', b'Masculin'), (b'F', b'Feminin')], max_length=1)),
                ('avatar', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
